# Generated by Django 5.2.17 on 2026-09-03 11:25
# Countries data migration added to populate countries table with initial data of all countries in the world. The data is stored in a JSON file named countries.json located in the same directory as this migration file.

import json
from pathlib import Path
import django.db.models.deletion
from django.db import migrations, models

def populate_countries(apps, schema_editor):
    Country = apps.get_model('holidays', 'Country')
    countries_data = json.loads((Path(__file__).parent / "migration_data" / "0002_countries.json").read_text())
    for country_data in countries_data:
        Country.objects.create(**country_data)


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='destination_images/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='holidays.country')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='holidays.holiday')),
            ],
        ),
        migrations.RunPython(populate_countries),
    ]
