# Generated by Django 5.2.17 on 2026-09-03 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_country_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='holiday',
        ),
        migrations.CreateModel(
            name='HolidayDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_holidays', to='holidays.destination')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_destinations', to='holidays.holiday')),
            ],
            options={
                'unique_together': {('holiday', 'destination')},
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='holiday',
            field=models.ManyToManyField(related_name='destinations', through='holidays.HolidayDestination', to='holidays.holiday'),
        ),
    ]
