# Generated by Django 5.2.17 on 2026-09-16 06:39

import django.db.models.deletion
import holidays.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0003_remove_destination_holiday_holidaydestination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('check_in', holidays.fields.TimePickerField(blank=True, null=True)),
                ('check_out', holidays.fields.TimePickerField(blank=True, null=True)),
                ('booking_reference', models.CharField(blank=True, max_length=30, null=True)),
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
                ('accommodation_type', models.CharField(choices=[('HOT', 'Hotel'), ('HOS', 'Hostel'), ('RES', 'Resort'), ('APA', 'Apartment / Flat'), ('BNB', 'Bed and Breakfast'), ('HOM', 'Homestay / Guesthouse'), ('GLA', 'Glamping'), ('CAM', 'Campsite'), ('CAR', 'Caravan'), ('CAB', 'Cabin')], default='HOT', max_length=3)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(upload_to='accommodation_covers/')),
            ],
        ),
        migrations.AlterField(
            model_name='holiday',
            name='end_date',
            field=holidays.fields.DatePickerField(),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='start_date',
            field=holidays.fields.DatePickerField(),
        ),
        migrations.AlterField(
            model_name='holidaydestination',
            name='arrival_date',
            field=holidays.fields.DatePickerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holidaydestination',
            name='departure_date',
            field=holidays.fields.DatePickerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holidaydestination',
            name='accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_accommodation', to='holidays.accommodation'),
        ),
    ]
